# simple.gocd.yaml
pipelines:
  pipe1:
    group: simple
    materials:
      mygit: # this is the name of material
        # says about type of material and url at once
        git: https://github.com/saivenkat288/goCD-Test
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              resources:
                - python
              tasks:
                - exec:
                    command: ls
                - exec:
                    command: /usr/bin/python
                    arguments:
                      - -v
                      - simple.py
